### ISSUE TITLE
Support for Laboratory and other irregular meetings time

### ISSUE THREAD

**Issue by jaures** [dot-slash-CS/WebAdvisor-Scheduler#11]
I noticed in the classes.py file in the templates folder, as far as I could tell, there is no way to deal with classes (like many ENGI classes) where they have laboratory components which can be on different days and times than the lecture component.

class Meeting

	 def __init__(self,meetingType,campus,startTime,endTime,professorName,room,recurrence):
		 self.meetingType = meetingType # string # "Lecture"
		 self.campus = campus # string # "Newark"
		 self.startTime = startTime #Time object  datetime.time() # Either make these a linked list
		 self.endTime = endTime #Time object  datetime.time()   # or link them togther in a tuple
                                                                                                           # and store in some List
		 self.professorName = professorName #name string
		 self.room = room #string
		 self.recurrence = recurrence #list of strings

If you guys wanted to continue using this method, you could have start and end times as tuples (or lists) where the first element represents the start and the second element represents the end time, and have these pairs appended to like a total meetings list, where you can later just check the length of these lists to determine if the course has just a lecture part or if it has labs or other irregular meet times. Doing so will also mean you'll have to make the recurrence attribute for the Meeting class a list too linked to the list of tuples mentioned earlier. You could also just make the startTime, endTime, and recurrence be linked lists making it easy to fix the issue without too many crazy workarounds. I think this would probably be the most painless solution.

If it is not too much of a concern at the moment and for the sake of pushing through a beta ASAP, I can close this issue and post it under the Forum issues thread instead until we get to it. However, considering that if we don't consider these other unaccounted for meeting times for the course, it'll lead to conflicts later when trying to generate schedules if they aren't away of these extra meeting times.

**Comment by cpkurotori** [comment]
If you look at the Section class object, the "meetings" member will actually be a list of Meeting class objects. This is for the case in which there are multiple "types" (Laboratory and Lecture).  So, for example, many Chemistry classes that have a lecture and laboratory, there will be two meetings in the list, each with its own start time and end times. Prediction team will have to take both of these into account for the section. 

Does this cover your concern or is there more?

```
class Section:
	def __init__(self,startDate,endDate,meetings,number):
		self.startDate = startDate # date(2017,3,5) == March 5th,2017
		self.endDate = endDate # date(2017,4,15) == April 15th, 2017
		self.meetings = meetings  #list of meeting objects
		self.section_number = section_number # string # "02" #
```

EDIT: better clarify some parts

**Comment by jaures** [comment]
You are absolutely right, sorry glossed over that part. Yeah that takes care of it then.
